# Tasca S10.01. APIs REST

## Nivell 1

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.

1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

Llista de publicacions (/posts)
Llista d’usuaris (/users)
Llista de tasques (/todos)

In [ ]:
import requests
import pandas as pd

response = requests.get("https://jsonplaceholder.typicode.com/posts")
print(response.status_code)
print()
print(response.json())

response = requests.get("https://jsonplaceholder.typicode.com/users")
print(response.status_code)
print()
print(response.json())

response = requests.get("https://jsonplaceholder.typicode.com/todos")
print(response.status_code)
print()
print(response.json())

200


2. Mostra per pantalla:

La quantitat total de cada recurs.
El codi d'estat de cada petició.

In [53]:
response = requests.get("https://jsonplaceholder.typicode.com/posts")
print("Status code: ", response.status_code,)
print()
data = response.json()
print("Cantidad total: ", len(data))
print()

response = requests.get("https://jsonplaceholder.typicode.com/users")
print("Status code: ", response.status_code)
print()
data = response.json()
print("Cantidad total: ", len(data))
print()

response = requests.get("https://jsonplaceholder.typicode.com/todos")
print("Status code: ", response.status_code)
print()
data = response.json()
print("Cantidad total: ", len(data))

Status code:  200

Cantidad total:  100

Status code:  200

Cantidad total:  10

Status code:  200

Cantidad total:  200

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [54]:
response = requests.get("https://jsonplaceholder.typicode.com/posts/9999")

print(response.status_code)

404

4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [55]:
new_post = {'userId': 101, 'title': 'sunt aut', 'body': 'quia et suscipit'}
r = requests.post("https://jsonplaceholder.typicode.com/posts", json=new_post)
print(r.status_code)
print()
print(r.json())

201

{'userId': 101, 'title': 'sunt aut', 'body': 'quia et suscipit', 'id': 101}

5. Fes una petició PATCH per modificar parcialment una publicació existent.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [56]:
r = requests.patch("https://jsonplaceholder.typicode.com/posts/100", json={"title": "El nuevo título"})
print(r.status_code)
print()
print(r.json())

200

{'userId': 10, 'id': 100, 'title': 'El nuevo título', 'body': 'cupiditate quo est a modi nesciunt soluta\nipsa voluptas error itaque dicta in\nautem qui minus magnam et distinctio eum\naccusamus ratione error aut'}

6. Fes una petició DELETE sobre una publicació.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [58]:
r = requests.delete("https://jsonplaceholder.typicode.com/posts/95")
print(r.status_code)
print()
print(r.json())

200

{}

## Nivell 2

Interacció amb una API pública real

1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

In [ ]:
# U.S. Department of the Treasury Data API https://api.fiscaldata.treasury.gov/services/api/fiscal_service

# https://fiscaldata.treasury.gov/api-documentation/

response = requests.get("https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/avg_interest_rates")
print(response.status_code)
print()
print(response.json())

200


2. Llegeix la documentació de l'API:

Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.

- /v2/accounting/od/avg_interest_rates
- /v1/accounting/tb/esf1_balances

Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.

- ?filter=reporting_fiscal_year:in:(2007,2008,2009,2010)
- ?sort=-record_date

Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

In [91]:

response = requests.get("https://api.fiscaldata.treasury.gov/services/api/fiscal_service//v2/accounting/od/redemption_tables")
print(response.status_code)
print()
print(response.json())

200


3. Fes una petició GET senzilla:

Mostra el codi d'estat de la resposta.
Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [ ]:
response = requests.get("https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange")
print(response.status_code)
print()
data = response.json()

df = pd.DataFrame(data['data'])

display(df.head(2))
print()
display(df.tail(3))
print()
first_record = data['data'][0]
print(first_record['country'], "-", first_record["record_date"])
print()
for record in data['data'][:3]:
    print(record['record_date'], "-", record['exchange_rate'])

200

,record_date,country,currency,country_currency_desc,exchange_rate,effective_date,src_line_nbr,record_fiscal_year,record_fiscal_quarter,record_calendar_year,record_calendar_quarter,record_calendar_month,record_calendar_day
0,2001-03-31,Afghanistan,Afghani,Afghanistan-Afghani,78400.0,2001-03-31,1,2001,2,2001,1,03,31
1,2001-03-31,Albania,Lek,Albania-Lek,142.4,2001-03-31,2,2001,2,2001,1,03,31

,record_date,country,currency,country_currency_desc,exchange_rate,effective_date,src_line_nbr,record_fiscal_year,record_fiscal_quarter,record_calendar_year,record_calendar_quarter,record_calendar_month,record_calendar_day
97,2001-03-31,Madagascar,Franc,Madagascar-Franc,6460.0,2001-03-31,101,2001,2,2001,1,03,31
98,2001-03-31,Malawi,Kwacha,Malawi-Kwacha,79.75,2001-03-31,102,2001,2,2001,1,03,31
99,2001-03-31,Malaysia,Ringgit,Malaysia-Ringgit,3.8,2001-03-31,103,2001,2,2001,1,03,31

Afghanistan - 2001-03-31

2001-03-31 - 78400.0
2001-03-31 - 142.4
2001-03-31 - 76.539

4. Converteix les dades a un DataFrame de pandas:

Mostra les primeres files del DataFrame.

In [107]:
response = requests.get("https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/avg_interest_rates")
print(response.status_code)
print()
data = response.json()

df = pd.DataFrame(data['data'])

display(df.head(5))

200

,record_date,security_type_desc,security_desc,avg_interest_rate_amt,src_line_nbr,record_fiscal_year,record_fiscal_quarter,record_calendar_year,record_calendar_quarter,record_calendar_month,record_calendar_day
0,2001-01-31,Marketable,Treasury Notes,6.096,2,2001,2,2001,1,01,31
1,2001-01-31,Marketable,Treasury Bonds,8.450,3,2001,2,2001,1,01,31
2,2001-01-31,Marketable,Treasury Inflation-Indexed Notes,3.772,4,2001,2,2001,1,01,31
3,2001-01-31,Marketable,Treasury Inflation-Indexed Bonds,3.866,5,2001,2,2001,1,01,31
4,2001-01-31,Marketable,Federal Financing Bank,8.917,6,2001,2,2001,1,01,31

## Nivell 3

API d'Open Data Barcelona

1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show. .

In [36]:
# https://opendata-ajuntament.barcelona.cat/data/api/action/

# https://opendata-ajuntament.barcelona.cat/data/api/action/current_package_list_with_resources

In [ ]:
r = requests.get("https://opendata-ajuntament.barcelona.cat/data/api/action/package_search")

print(r.status_code)

200

In [4]:
data = r.json()
print(type(data))     # tells you: is this a dict or a list?

<class 'dict'>

In [5]:
print(data.keys())

dict_keys(['help', 'success', 'result'])

In [6]:
print(type(data["result"]))

<class 'dict'>

In [7]:
print(data["result"].keys())

dict_keys(['count', 'sort', 'facets', 'results', 'search_facets'])

In [8]:
print(type(data["result"]["results"]))   # should say <class 'list'>
print(len(data["result"]["results"]))     # how many datasets came back

<class 'list'>
10

In [9]:
first = data["result"]["results"][0]
print(type(first))          # dict
print(first.keys())          # shows fields like 'title', 'name', 'notes', 'resources'...

<class 'dict'>
dict_keys(['notes_translated', 'geolocation', 'dades_alt_valor', 'url_tornada', 'dataset_fields_description', 'fuente', 'tag', 'private', 'num_tags', 'code', 'frequency', 'id', 'title_translated', 'metadata_modified', 'author', 'author_email', 'isopen', 'long_format', 'state', 'version', 'mar_od', 'relationships_as_object', 'department', 'creator_user_id', 'type', 'resources', 'token_required', 'decalatgeNum', 'tags', 'ODS_Principal_agenda_2030', 'fecha_publicacion', 'ODS_Colateral2_agenda_2030', 'ODS_Colateral1_agenda_2030', 'license_id', 'hide_url', 'relationships_as_subject', 'license_title', 'groups', 'num_resources', 'organization', 'name', 'url', 'notes', 'owner_org', 'load_type', 'api', 'license_url', 'historical', 'title', 'revision_id', 'extras'])

In [11]:
for dataset in data["result"]["results"]:
    print(dataset["title"])

Area (m²) of real estate properties transmitted by sale transaction, based on notarials records, by property use
Number of real estate property transactions, based on notarial records, by property use
Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council
Receipts and quota of the register of the Vados Tax of the Barcelona City Council
Receipts and charges from the motor vehicle tax roll of the Barcelona City Council
Immigrants
Emigrants
Cancellations for undue inscription
Deaths
Registrations by omission

In [1]:
import pandas as pd 
import requests

BASE = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/"

BASE_2 = "https://opendata-ajuntament.barcelona.cat/data/api/action/"

In [2]:

r = requests.get(BASE + "package_search", params={"q": "Deaths"})
print(r.status_code)

200

In [3]:
data = r.json()
print(data.keys())

dict_keys(['help', 'success', 'result'])

In [4]:
print(data["result"].keys())

dict_keys(['count', 'sort', 'facets', 'results', 'search_facets'])

In [5]:
results = data["result"]["results"]
print(len(results))

for dataset in results:
    print(dataset["title"])

1
Deaths

In [6]:
for dataset in results:
    print(dataset["title"], "-", dataset["name"])

Deaths - pad_def_mdbas

In [7]:
# https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=pad_def_mdbas

r = requests.get(BASE + "package_show", params={"id": "pad_def_mdbas"})
print(r.status_code)

data = r.json()
print(data["result"].keys())

200
dict_keys(['notes_translated', 'geolocation', 'dades_alt_valor', 'url_tornada', 'dataset_fields_description', 'fuente', 'tag', 'private', 'num_tags', 'code', 'frequency', 'id', 'title_translated', 'metadata_modified', 'author', 'author_email', 'isopen', 'long_format', 'state', 'version', 'mar_od', 'relationships_as_object', 'department', 'creator_user_id', 'type', 'resources', 'token_required', 'decalatgeNum', 'tags', 'ODS_Principal_agenda_2030', 'fecha_publicacion', 'ODS_Colateral2_agenda_2030', 'ODS_Colateral1_agenda_2030', 'license_id', 'hide_url', 'relationships_as_subject', 'license_title', 'groups', 'num_resources', 'organization', 'name', 'url', 'notes', 'owner_org', 'load_type', 'qa', 'api', 'license_url', 'historical', 'title', 'revision_id', 'extras'])

In [8]:
resources = data["result"]["resources"]

for res in resources:
    print(res["id"], "-", res["format"], "-", res["name"])

840f6761-46c5-4bf1-93e5-906bec0664bc - CSV - 2025_pad_def_mdbas.csv
1418ae14-307f-4927-8dfa-90fc4e8a1527 - JSON - 2025_pad_def_mdbas.json
8f03667c-863b-4507-a6cd-070b868dd941 - CSV - 2024_pad_def_mdbas.csv
ed2198a2-29e9-4af7-b86f-7945370c9497 - JSON - 2024_pad_def_mdbas.json
ef19e049-9f2d-4b10-b1a0-cb823c215871 - CSV - 2023_pad_def_mdbas.csv
e78ef972-e0c0-4830-885e-845d5affe56f - JSON - 2023_pad_def_mdbas.json
adca6eba-7560-422c-a419-73b274584cbc - CSV - 2022_pad_def_mdbas.csv
7c73c228-5f75-4824-88f4-a4a0bd3646e9 - JSON - 2022_pad_def_mdbas.json
b32ba4cd-ed5b-4dae-927b-ca3014d09478 - CSV - 2021_pad_def_mdbas.csv
f08265b4-e22b-45a5-934a-8055f71f2d4e - JSON - 2021_pad_def_mdbas.json
da13237f-36bf-43a4-b734-6aca26c23e55 - CSV - 2020_pad_def_mdbas.csv
3ad5e9c7-d719-4a7c-9fd6-4aba73bba7df - JSON - 2020_pad_def_mdbas.json
b2e2b5d4-8913-4c8b-99fb-33090da70b9b - CSV - 2019_pad_def_mdbas.csv
41262175-b4dd-409e-ac89-e3ada78dcfe9 - JSON - 2019_pad_def_mdbas.json
9bf86ba9-91c6-4482-aebb-3e8575629b02 - CSV - 2018_pad_def_mdbas.csv
f39b9df8-fd11-4b36-a094-d9eac0e69bcb - JSON - 2018_pad_def_mdbas.json
d1fcc5bb-4bbf-489b-9314-1c250cfd23d9 - CSV - 2017_pad_def_mdbas.csv
481d63e7-9424-4866-b6d4-14fbb23f4c15 - JSON - 2017_pad_def_mdbas.json
ee139479-755d-4e77-938c-6a91a345d371 - CSV - 2016_pad_def_mdbas.csv
f82e6ae8-0c5f-4716-81d3-01c92e0c3b17 - JSON - 2016_pad_def_mdbas.json
5a5bf350-64b0-41cf-a1cd-bc7bd3b72e64 - CSV - 2015_pad_def_mdbas.csv
453a5c37-0220-4e1b-ae2c-a810da088ba0 - JSON - 2015_pad_def_mdbas.json
512eb90e-7b46-4067-b20c-d639803f102a - CSV - 2014_pad_def_mdbas.csv
4eb03447-12c4-4b28-a82b-08b820157c50 - JSON - 2014_pad_def_mdbas.json
43dbfa31-84b2-418e-b34a-57b3181752ce - CSV - 2013_pad_def_mdbas.csv
8763d5ee-753d-42e7-9130-0334e3d5d406 - JSON - 2013_pad_def_mdbas.json
cff46db7-3d39-49c1-a3a6-80101c29b9b1 - CSV - 2012_pad_def_mdbas.csv
f0eab153-e5a9-45cc-bf7d-c1be7f079bda - JSON - 2012_pad_def_mdbas.json
1266a6eb-84cf-44c4-8bd4-c17bd5a7a68f - CSV - 2011_pad_def_mdbas.csv
9af01e07-e6dc-4b6d-ab25-c0b926bf6f31 - JSON - 2011_pad_def_mdbas.json
46150ecf-ded7-4fd5-87de-a25f1e53f55b - CSV - 2010_pad_def_mdbas.csv
7a7a79bd-baf8-4aaa-8b84-a4f60ab745b4 - JSON - 2010_pad_def_mdbas.json
11b3a648-6b65-4f05-a3c2-e1d20f8feee0 - CSV - 2009_pad_def_mdbas.csv
11294924-6c15-477f-bbd4-f5b771550427 - JSON - 2009_pad_def_mdbas.json
f9060a43-8b4c-452a-b225-9b80cc8c1e1c - CSV - 2008_pad_def_mdbas.csv
a9ddbeaa-f9fc-4359-b24a-5b7ee526edda - JSON - 2008_pad_def_mdbas.json
064d224a-75f8-4de4-aca3-10f8c2a36afb - CSV - 2007_pad_def_mdbas.csv
9adb21e2-160d-4c86-8192-84f4fe526602 - JSON - 2007_pad_def_mdbas.json
02bbc4ef-ebd3-4e74-86be-fbe63ed4fb17 - CSV - 2006_pad_def_mdbas.csv
23910f6f-06cd-464b-9a10-8aa1a6cce52b - JSON - 2006_pad_def_mdbas.json
31848ce3-9c43-4bc0-b6dc-bee9fd0af757 - CSV - 2005_pad_def_mdbas.csv
72fc4924-6fb2-4292-8b23-c5bdbe2987ab - JSON - 2005_pad_def_mdbas.json
82120dff-f550-4ade-ab53-7f0e87401656 - CSV - 2004_pad_def_mdbas.csv
2f5e9f63-405c-4141-add9-883b5f25bfd2 - JSON - 2004_pad_def_mdbas.json
4be4f720-9d76-423d-8040-e1443e8d7ca4 - CSV - 2003_pad_def_mdbas.csv
74955ad2-645c-41b5-82f5-583d1ed2f554 - JSON - 2003_pad_def_mdbas.json
a99b45fa-1050-4e1e-8e9c-8aa0c008ff7d - CSV - 2002_pad_def_mdbas.csv
b3b5c67c-69a5-4fb9-8c5b-6f2cb0ec05f8 - JSON - 2002_pad_def_mdbas.json
b40b22ba-2bae-4dfe-987f-7ec185d518e2 - CSV - 2001_pad_def_mdbas.csv
4255de7e-eea8-4a23-b9be-d73552f3f2fb - JSON - 2001_pad_def_mdbas.json
1de949b0-7f24-4c91-a439-2558893b365f - CSV - 2000_pad_def_mdbas.csv
814aa96f-77da-4e30-aea9-854a5fb3e714 - JSON - 2000_pad_def_mdbas.json
4cb6c148-0985-4a30-8405-f2ea57be6283 - CSV - 1999_pad_def_mdbas.csv
f06118c5-86fb-400d-bec9-9f43e655ed8a - JSON - 1999_pad_def_mdbas.json
8d03a625-61e9-4783-832d-07a4f9f2107d - CSV - 1998_pad_def_mdbas.csv
ee09d027-39ce-469b-83e5-97e26cf94234 - JSON - 1998_pad_def_mdbas.json
a5c96830-5616-4106-9901-f9fcde3c70cc - CSV - 1997_pad_def_mdbas.csv
32d415d4-4a3c-458b-ab75-6423318fc844 - JSON - 1997_pad_def_mdbas.json

2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [54]:
# hacemos comprobación de que el formato json no tiene la función de data_store activa, así que escogemos el formato CSV que sí lo tiene.x

r = requests.get(BASE + "resource_show", params={
    "id": "840f6761-46c5-4bf1-93e5-906bec0664bc"
})
print(r.status_code)

info = r.json()["result"]
print(info.get("datastore_active"))
print(info.get("format"))

200
True
CSV

In [9]:
# Ejemplo de la web: https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=f7134b6f-95ce-4b83-bacd-6f411bd9c1f0

r = requests.get(BASE + "datastore_search", params={
    "resource_id": "840f6761-46c5-4bf1-93e5-906bec0664bc",
    "limit": 100
})
print(r.status_code)

200

In [10]:
data = r.json()
print(data["result"].keys())

dict_keys(['resource_id', 'fields', 'records', '_links', 'limit', 'total'])

3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [11]:
records = data["result"]["records"]
print(len(records))
print(records[0])

100
{'Codi_Districte': '1', 'Nom_Districte': 'Ciutat Vella', 'Nom_Barri': 'el Raval', 'AEB': '1', 'Seccio_Censal': '1001', 'Valor': '11', 'Codi_Barri': '1', '_id': 1, 'Any': '2025'}

4. Converteix els resultats a un DataFrame.

In [12]:

df = pd.DataFrame(records)
print(df.shape)
df.head()

(100, 9)

,Codi_Districte,Nom_Districte,Nom_Barri,AEB,Seccio_Censal,Valor,Codi_Barri,_id,Any
0,1,Ciutat Vella,el Raval,1,1001,11,1,1,2025
1,1,Ciutat Vella,el Raval,1,1002,18,1,2,2025
2,1,Ciutat Vella,el Raval,2,1003,12,1,3,2025
3,1,Ciutat Vella,el Raval,2,1004,16,1,4,2025
4,1,Ciutat Vella,el Raval,3,1005,12,1,5,2025

5. Desa el DataFrame en un fitxer .csv.

In [13]:
df.to_csv("opendata_bcn_output_Deaths.csv", index=False)